UPDATE alpha_langues SET libelle_langue = 'Kiswahili' WHERE libelle_langue = 'Kiswahili';
UPDATE alpha_langues SET libelle_langue = 'Pendjabi' WHERE libelle_langue = 'Panjâbî';
UPDATE alpha_langues SET libelle_langue = 'Bengali' WHERE libelle_langue = 'Bangla (Bengali)';
UPDATE alpha_langues SET libelle_langue = 'Bengali' WHERE libelle_langue = 'Bangladaise';
UPDATE alpha_langues SET libelle_langue = 'Bengali' WHERE libelle_langue = 'Bangladishi';
UPDATE alpha_langues SET libelle_langue = 'Bengali' WHERE libelle_langue = 'Bangli';
UPDATE alpha_langues SET libelle_langue = 'Wolof' WHERE libelle_langue = 'Baol';
UPDATE alpha_langues SET libelle_langue = 'Wolof' WHERE libelle_langue = 'Baoulé';
UPDATE alpha_langues SET libelle_langue = 'Berbère' WHERE libelle_langue = 'Berb';
UPDATE alpha_langues SET libelle_langue = 'Créole' WHERE libelle_langue = 'Cr';
UPDATE alpha_langues SET libelle_langue = 'Ewe' WHERE libelle_langue = 'Eve';
UPDATE alpha_langues SET libelle_langue = 'Foula' WHERE libelle_langue = 'Peuhl';
UPDATE alpha_langues SET libelle_langue = 'Français' WHERE libelle_langue = 'Fran';
UPDATE alpha_langues SET libelle_langue = 'Français' WHERE libelle_langue = 'Francais (un peu)';
UPDATE alpha_langues SET libelle_langue = 'Géorgien' WHERE libelle_langue = 'Georgien';
UPDATE alpha_langues SET libelle_langue = 'Grec' WHERE libelle_langue = 'Grecque';
UPDATE alpha_langues SET libelle_langue = 'Ijaw' WHERE libelle_langue = 'Ijaw, itsekiri, maruba';
UPDATE alpha_langues SET libelle_langue = 'Hindi' WHERE libelle_langue = 'Indi';
UPDATE alpha_langues SET libelle_langue = 'Lingala' WHERE libelle_langue = 'Ingala';
UPDATE alpha_langues SET libelle_langue = 'Jaffna (dialecte Tamoul)' WHERE libelle_langue = 'Jaffna';
UPDATE alpha_langues SET libelle_langue = 'Letton' WHERE libelle_langue = 'Lettonien';
UPDATE alpha_langues SET libelle_langue = 'Mongol' WHERE libelle_langue = 'Mongole';
UPDATE alpha_langues SET libelle_langue = 'Népalais' WHERE libelle_langue = 'Nepalais';
UPDATE alpha_langues SET libelle_langue = 'Ousbek' WHERE libelle_langue = 'Ousb';
UPDATE alpha_langues SET libelle_langue = 'Punjabi' WHERE libelle_langue = 'Panjâbî';
UPDATE alpha_langues SET libelle_langue = 'Pachto (Pashto, Pachtoune)' WHERE libelle_langue = 'Patchoun';
UPDATE alpha_langues SET libelle_langue = 'Pachto (Pashto, Pachtoune)' WHERE libelle_langue = 'Pashto';
UPDATE alpha_langues SET libelle_langue = 'Filipino' WHERE libelle_langue = 'Philippin';
UPDATE alpha_langues SET libelle_langue = 'Polonais' WHERE libelle_langue = 'Polonais / russe';
UPDATE alpha_langues SET libelle_langue = 'Senifou' WHERE libelle_langue = 'Senifou et bambara';
UPDATE alpha_langues SET libelle_langue = 'Cingalais (Cinghalais, Singhalais)' WHERE libelle_langue = 'Cingalais';
UPDATE alpha_langues SET libelle_langue = 'Cingalais (Cinghalais, Singhalais)' WHERE libelle_langue = 'Cinghalais';
UPDATE alpha_langues SET libelle_langue = 'Cingalais (Cinghalais, Singhalais)' WHERE libelle_langue = 'Singhalais';
UPDATE alpha_langues SET libelle_langue = 'Cingalais (Cinghalais, Singhalais)' WHERE libelle_langue = 'Sri lankais';
UPDATE alpha_langues SET libelle_langue = 'Cingalais (Cinghalais, Singhalais)' WHERE libelle_langue = 'Singalais';
UPDATE alpha_langues SET libelle_langue = 'Kiswahili (Swahili)' WHERE libelle_langue = 'Swahili';
UPDATE alpha_langues SET libelle_langue = 'Kiswahili (Swahili)' WHERE libelle_langue = 'Kiswahili';
UPDATE alpha_langues SET libelle_langue = 'Tagalog (Tagal)' WHERE libelle_langue = 'Tagalug';
UPDATE alpha_langues SET libelle_langue = 'Thaï' WHERE libelle_langue = 'Tha';
UPDATE alpha_langues SET libelle_langue = 'Turc' WHERE libelle_langue = 'Turque';
UPDATE alpha_langues SET libelle_langue = 'Ukrainien' WHERE libelle_langue = 'Ukrainienne';
UPDATE alpha_langues SET libelle_langue = 'Anglais' WHERE libelle_langue = "Un peu d'anglais";
UPDATE alpha_langues SET libelle_langue = 'Français' WHERE libelle_langue = 'Un peu de français';
UPDATE alpha_langues SET libelle_langue = 'Vietnamien' WHERE libelle_langue = 'Vietnamienne';
UPDATE alpha_langues SET libelle_langue = 'Wenzhou (Oujiang)' WHERE libelle_langue = 'Wenzhou';
UPDATE alpha_langues SET libelle_langue = 'Wenzhou (Oujiang)' WHERE libelle_langue = 'Wenzhouch';
UPDATE alpha_langues SET libelle_langue = 'Wolof (Baol)' WHERE libelle_langue = 'Wolof';
